[package]
name = "beta-example"
version = "1.0.0-beta.6.rc-3.2"
edition = "2024"

[dependencies]
svgr-macro.workspace = true
lazy_static = "1.4.0"
libm = "0.2.1"
rand = "0.8.5"
hello-world-example = { path = "../hello-world", default-features = false }
marketing-example = { path = "../marketing", default-features = false }
podcast-example = { path = "../podcast", default-features = false }
tiktok-example = { path = "../tiktok", default-features = false }
fframes = { workspace = true, features = ["h264", "libav-agree-gpl"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fframes_renderer = { path = "../../fframes-renderer" }
fframes_skia_renderer = { workspace = true, features = ["vulkan"] }

[features]
default = ["renderer"]
renderer = [
	"fframes/compile-time-svgtree",
	"hello-world-example/renderer",
	"marketing-example/renderer",
	"podcast-example/renderer",
	"tiktok-example/renderer",
]

[lib]
name = "beta_example"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "beta_example_bin"
path = "src/main.rs"
required-features = ["renderer"]
