[package]
name = "hello-word-bridge-example"
version = "1.0.0-beta.4"
authors = ["Dmitriy Kovalenko <dmtr.kovalenko@outlook.com>"]
edition = "2018"

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]
path = "./lib.rs"

[dependencies]
wasm-bindgen = "0.2.95"
fframes-editor-controller = { path = "../../../../fframes-editor-controller" }
hello-world-example = { path = "../../", default-features = false }
