[package]
name = "hello-word-bridge-example"
version = "1.0.0-beta.6.rc-3.2"
authors = ["Dmitriy Kovalenoko <dmtr.kovalenko@outlook.com>"]
edition = "2018"

[package.metadata.wasm-pack.profile.profiling]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]
path = "./lib.rs"

[dependencies]
wasm-bindgen = "0.2.100"
fframes-editor-controller = { path = "../../../../fframes-editor-controller" }
hello-world-example = { path = "../../", default-features = false }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
	'cfg(wasm_bindgen_unstable_test_coverage)',
] }
