[package]
name = "fframes-editor-controller"
description = "Helper wasm module that provies fframes bindings for the web WASM editor"
license = "MIT"
version = "1.0.0-beta.6.rc-2.1"
authors = ["Dmitriy Kovalenko <dmtr.kovalenko@outlook.com>"]
edition = "2021"
homepage = "https://fframes.studio"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fframes = { workspace = true, default-features = false }
lazy_static = "1.4.0"
console_error_panic_hook = "0.1.7"
wasm-bindgen-futures = "0.4.42"
wasm-bindgen = { workspace = true, features = ["serde-serialize"] }
js-sys = "0.3.69"
futures = "0.3.30"
serde-wasm-bindgen = "0.6.5"
# This is only needed for the wasm32 target for uuid
getrandom = { version = "0.2.15", features = ["js"] }
