[package]
name = "fframes-editor-controller"
version = "0.1.0"
authors = ["Dmitriy Kovalenko <dmtr.kovalenko@outlook.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[build]
target = "wasm32-unknown-unknown"

[dependencies]
fframes = { path = "../fframes", default-features=false }
lazy_static = "1.4.0"
console_error_panic_hook = "0.1.6"
wasm-bindgen-futures= "0.4.28"
wasm-bindgen = { version = "0.2.74", features = ["serde-serialize"] }
js-sys = "0.3.55"
futures = "0.3.27"
