[package]
name = "marketing-example"
version = "1.0.0-beta.6.rc-3.2"
edition = "2021"

[dependencies]
fframes.workspace = true
# This is only needed for the wasm32 target for uuid
getrandom = { version = "0.2.15", features = ["js"] }

[dev-dependencies]
fframes_test_utils = {path="../../fframes-test-utils"}
futures = "0.3.17"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fframes_renderer ={path="../../fframes-renderer"}

[features]
default=["renderer"]
renderer=["fframes/compile-time-svgtree"]

[lib]
name = "marketing_example"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "marketing_example_bin"
path = "src/main.rs"
required-features=["renderer"]
