[package]
name = "marketing-example"
version = "0.1.0"
edition = "2021"

[dependencies]
fframes = {path="../../fframes"}

[dev-dependencies]
fframes_test_utils = {path="../../fframes-test-utils"}
futures = "0.3.17"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fframes_renderer ={path="../../fframes-renderer"}

[features]
default=["renderer"]
renderer=["fframes/compile-time-svgtree"]


[lib]
name = "marketing_example"
path = "src/lib.rs"

[[bin]]
name = "marketing_example_bin"
path = "src/main.rs"
required-features=["renderer"]