[package]
name = "fframes_renderer"
version = "0.1.0"
edition = "2018"

[dependencies]
svgr = { path = "../../resvg" }
usvgr = { path = "../../resvg/usvgr" }
usvgr-text-layout = { path = "../../resvg/usvgr-text-layout" }
rayon = "1.5.1"
colored = "2"
indicatif = "0.16.2"
once_cell = "1.10.0"
lazy_static = "1.3.0"
lyon = "0.17.10"
wgpu = "0.12.0"
bytemuck = "1.9.1"
futures = "0.3.1"
image = "0.24.3"
ffmpeg-next = "5.1.1"

syn = { version = "1", features = ["full", "parsing", "extra-traits"] }
uuid = { version = "0.8", features = ["v4"] }

svgr-macro = { path="../svgr-macro" }
fframes = {path="../fframes"}
media-loader = {path="../media-loader"}

[build-dependencies]
cc = "1.0"

