[package]
name = "fframes_renderer"
description = "Renderer and encoder for fframes"
version = "1.0.0-beta.6.rc-3.2"
edition = "2021"
homepage = "https://fframes.studio"
authors = ["Dmitriy Kovalenko <dmtr.kovalenko@outlook.com>"]
license = "MIT"

[dependencies]
svgr = { workspace = true, optional = true }
rayon = "1.5.1"
colored = "2"
indicatif = "0.16.2"
once_cell = "1.10.0"
lazy_static = "1.3.0"
bytemuck = "1.15.0"
futures = "0.3.30"
image = "0.25.0"
memmap = "0.7.0"
syn = { version = "1", features = ["full", "parsing", "extra-traits"] }
uuid = { version = "1.8.0", features = ["v4"] }

svgr-macro.workspace = true
fframes.workspace = true
ffmpeg-sys-fframes.workspace = true

[build-dependencies]
cc = "1.0"

[features]
default = ["cpu_renderer"]
cpu_renderer = ["svgr"]
h264 = ["ffmpeg-sys-fframes/build-lib-x264"]
h265 = ["ffmpeg-sys-fframes/build-lib-x265"]
videotoolbox = ["ffmpeg-sys-fframes/build-videotoolbox"]
audiotoolbox = ["ffmpeg-sys-fframes/build-audiotoolbox"]
aac = ["ffmpeg-sys-fframes/build-lib-aacplus"]
mp3lame = ["ffmpeg-sys-fframes/build-lib-mp3lame"]
opus = ["ffmpeg-sys-fframes/build-lib-opus"]
vpx = ["ffmpeg-sys-fframes/build-lib-vpx"]

# license stuff
libav-agree-gpl = ["ffmpeg-sys-fframes/build-license-gpl"]
libav-agree-nonfree = ["ffmpeg-sys-fframes/build-license-nonfree"]
libav-agree-version3 = ["ffmpeg-sys-fframes/build-license-version3"]
