[workspace]
resolver = "2"
members = [
    "e2e",
    "svgr-macro",
    "webvtt-parser",
    "fframes-renderer",
    "fframes-editor-controller",
    "fframes-test-utils",
    "fframes-media-loaders",
    # Examples 
    "examples/podcast",
    "examples/podcast/editor/editor-bridge",
    "examples/audio-announce",
    "examples/audio-announce/editor/editor-bridge",
    "examples/hello-world",
    "examples/hello-world/editor/editor-bridge",
    "examples/marketing",
    "examples/marketing/editor/editor-bridge",
    "examples/tiktok",
    "examples/tiktok/media",
    "examples/tiktok/editor/editor-bridge",
    "examples/marketing/editor/editor-bridge",
    "examples/low-poly-art",
    "examples/low-poly-art/editor/editor-bridge",
    "examples/beta",
    "examples/beta/editor/editor-bridge",
]

[workspace.dependencies]
# If you are working locally on renderer, just clone https://github.com/dmtrKovalenko/svgr 
# into the parent directory of fframes (as a sibling) and uncomment the following lines:
# svgr = { path = "../svgr/crates/svgr"}
# usvgr = { path = "../svgr/crates/usvgr"}
svgr = "0.43.1"
usvgr = "0.43.1"
ffmpeg-sys-fframes = { version = "7.0.3", features = ["build", "static", "build-lib-x264", "build-lib-x265", "build-license-gpl"] }

# fframes internal deps 
fframes-media-loaders = { path = "fframes-media-loaders", version = "1.0.0-beta.1" }
svgr-macro = { path = "svgr-macro", version = "1.0.0-beta.1" }
fframes-media-dir-macro = { path = "media-dir-macro", version = "1.0.0-beta.1" }
fframes = { path = "fframes", version = "1.0.0-beta.1" }
webvtt-parser = { path = "webvtt-parser", version = "1.0.0-beta.1" }

