[workspace]

members = [
    "svgr-macro",
    "media-loader",
    "webvtt-parser",
    "fframes-renderer",
    "fframes-editor-controller",
    "examples/marketing",
    "examples/marketing/editor/editor-bridge",
    "examples/podcast",
    "examples/podcast/editor/editor-bridge",
    "examples/hello-world",
    "examples/hello-world/editor/editor-bridge",
    "examples/tiktok",
    "examples/tiktok/editor/editor-bridge",
    "examples/beta",
    "examples/beta/editor/editor-bridge",
]

exclude = [
    
]

resolver="2"

