[workspace]
resolver = "2"
members = [
    "e2e",
    "svgr-macro",
    "webvtt-parser",
    "fframes-renderer",
    "fframes-editor-controller",
    "fframes-test-utils",
    "fframes-media-loaders",
    "examples/marketing",
    "examples/podcast",
    "examples/podcast/editor/editor-bridge",
    "examples/hello-world",
    "examples/hello-world/editor/editor-bridge",
    "examples/marketing",
    "examples/marketing/editor/editor-bridge",
    "examples/tiktok",
    "examples/tiktok/media",
    "examples/tiktok/editor/editor-bridge",
    "examples/marketing/editor/editor-bridge",
    "examples/low-poly-art",
    "examples/beta",
    "examples/beta/editor/editor-bridge",
]

[workspace.dependencies]
# This is a base CPU renderer which is a fork of another project. 
# Clone it in the same directlry as fframes from here https://github.com/dmtrKovalenko/svgr and 
# uncomment the following lines to run them together

# svgr = { path = "../resvg"}
# usvgr = { path = "../resvg/usvgr"}
# usvgr-text-layout = { path = "../resvg/usvgr-text-layout"}
svgr = "0.28.5"
usvgr = "0.28.5"
usvgr-text-layout = "0.28.5"

# fframes internal deps
webvtt-parser = { path = "webvtt-parser" }
fframes-media-loaders = { path = "fframes-media-loaders" }
