[package]
name = "beta-editor-bridge"
version = "1.0.0-beta.4"
authors = ["Dmitriy Kovalenko <dmtr.kovalenko@outlook.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "./lib.rs"

[dependencies]
wasm-bindgen = "0.2.95"
fframes-editor-controller = { path = "../../../../fframes-editor-controller" }
beta-example = { path = "../../", default-features = false }
marketing-example = { path = "../../../marketing", default-features = false }
tiktok-example  = { path = "../../../tiktok", default-features = false }
hello-world-example = { path = "../../../hello-world", default-features = false }
podcast-example = { path = "../../../podcast", default-features = false }
