// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../Utils.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as UseObservable from "../hooks/useObservable.bs.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as MediaResolvers from "./MediaResolvers";

var initial = {
  allMediaLoaded: false,
  mediaList: undefined
};

function reducer(state, action) {
  if (typeof action === "number") {
    return {
            allMediaLoaded: true,
            mediaList: state.mediaList
          };
  }
  if (action.TAG === /* InitMediaProcessing */0) {
    return {
            allMediaLoaded: state.allMediaLoaded,
            mediaList: Belt_MapString.fromArray(Belt_Array.map(Object.keys(action._0), (function (relativePath) {
                        return [
                                Utils.Path.getFilename(relativePath),
                                {
                                  TAG: /* Loading */0,
                                  _0: relativePath
                                }
                              ];
                      })))
          };
  }
  var media = action._1;
  return {
          allMediaLoaded: state.allMediaLoaded,
          mediaList: Belt_MapString.update(state.mediaList, action._0, (function (param) {
                  return {
                          TAG: /* Media */1,
                          _0: media
                        };
                }))
        };
}

var ObserverState = {
  initial: initial,
  reducer: reducer
};

var MediaLoaderObserver = UseObservable.MakeObserver(ObserverState);

var resolveAudio = MediaResolvers.resolveAudio;

var resolveSubtitles = MediaResolvers.resolveSubtitles;

var resolveFont = MediaResolvers.resolveFont;

var resolveImage = MediaResolvers.resolveImage;

function resolveMedia(name, media) {
  Curry._1(MediaLoaderObserver.dispatch, {
        TAG: /* MediaItemProcessed */1,
        _0: name,
        _1: media
      });
  return /* MediaResolved */0;
}

function processImports(imports, wasmController, options) {
  Curry._1(MediaLoaderObserver.dispatch, {
        TAG: /* InitMediaProcessing */0,
        _0: imports
      });
  return Promise.all(Belt_Array.keepMap(Object.entries(imports), (function (param) {
                      var moduleVal = param[1];
                      var moduleRelativePath = param[0];
                      var name = Utils.Path.getFilename(moduleRelativePath);
                      if (Utils.$$Option.unwrapOr(Belt_Option.map(options.ignoreMediaRegex, (function (regex) {
                                    return regex.test(moduleRelativePath);
                                  })), false)) {
                        return ;
                      } else {
                        return Belt_Option.map(name.endsWith(".mp3") ? resolveAudio : (
                                      name.endsWith(".vtt") ? resolveSubtitles : (
                                          name.endsWith(".ttf") || name.endsWith(".otf") ? resolveFont : (
                                              name.endsWith(".png") || name.endsWith(".jpg") || name.endsWith(".jpeg") ? Curry._1(resolveImage, options) : undefined
                                            )
                                        )
                                    ), (function (resolveFn) {
                                      return Curry._3(resolveFn, name, moduleVal, wasmController);
                                    }));
                      }
                    }))).then(function (param) {
              return Curry._1(MediaLoaderObserver.dispatch, /* MediaProcessingFinished */0);
            });
}

var $$Promise$1;

export {
  $$Promise$1 as $$Promise,
  ObserverState ,
  MediaLoaderObserver ,
  resolveAudio ,
  resolveSubtitles ,
  resolveFont ,
  resolveImage ,
  resolveMedia ,
  processImports ,
  
}
/* MediaLoaderObserver Not a pure module */
