[package]
name = "hello-world-example"
version = "1.0.0-beta.6.rc-3.2"
edition = "2024"

[dependencies]
fframes = { workspace = true, features = ["h264", "h265", "vpx", "libav-agree-gpl"] }

clap = { version = "4.3.4", features = ["derive"] }

[features]
default = ["renderer"]
renderer = ["fframes/compile-time-svgtree", "fframes/cli"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "hello_world_example"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "hello_world_example_bin"
path = "src/main.rs"
required-features = ["renderer"]
