[package]
name = "hello-world-example"
version = "1.0.0-beta.6.rc-3.2"
edition = "2021"

[dependencies]
fframes.workspace = true
clap = { version = "4.3.4", features = ["derive"] }
getrandom = { version = "0.2.15", features = ["js"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fframes_renderer = { workspace = true, features = ["h264", "libav-agree-gpl"] }

[features]
default = ["renderer"]
renderer = ["fframes/compile-time-svgtree"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "hello_world_example"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "hello_world_example_bin"
path = "src/main.rs"
required-features = ["renderer"]
