[package]
name = "fframes_test_utils"
version = "1.0.0-beta.4"
edition = "2021"

[lib]
path = "./src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fframes = { path = "../fframes" }
futures = "0.3"

[features]
default = ["compile-time-svgtree"]
compile-time-svgtree = ["fframes/compile-time-svgtree"]
