[package]
name = "pixel-example"
version = "1.0.0-beta.6.rc-3.2"
edition = "2024"

[dependencies]
fframes = { workspace = true, features = ["exif"] }
clap = { version = "4.3.4", features = ["derive"] }
image = "0.25.5"
rand = "0.8.5"
getrandom = { version = "0.2.15", features = ["js"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fframes_renderer = { workspace = true, features = [
	"h264",
	"h265",
	"libav-agree-gpl",
] }
fframes_skia_renderer = { workspace = true, features = ["vulkan", "debug"] }

[features]
cpu = []
default = ["renderer"]
renderer = ["fframes/compile-time-svgtree"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "pixel_memory_example"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "pixel_memory_example_bin"
path = "src/main.rs"
required-features = ["renderer"]
