// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as ReactSlider from "@radix-ui/react-slider";

var Root = {};

var Track = {};

var $$Range = {};

var Thumb = {};

var RadixSlider = {
  Root: Root,
  Track: Track,
  $$Range: $$Range,
  Thumb: Thumb
};

function Slider(Props) {
  var onValueChange = Props.onValueChange;
  var disabled = Props.disabled;
  var value = Props.value;
  var min = Props.min;
  var max = Props.max;
  var step = Props.step;
  var label = Props.label;
  var handleChange = React.useCallback((function (newValue) {
          return Curry._1(onValueChange, Caml_array.get(newValue, 0));
        }), [onValueChange]);
  return React.createElement(ReactSlider.Root, {
              value: [value],
              onValueChange: handleChange,
              step: step,
              min: min,
              max: max,
              disabled: disabled,
              children: null,
              className: "group relative flex h-4 w-24 touch-none select-none items-center data-[disabled]:opacity-50"
            }, React.createElement(ReactSlider.Track, {
                  children: React.createElement(ReactSlider.Range, {
                        className: "absolute h-full rounded-2xs bg-[var(--color-text)]"
                      }),
                  className: "relative h-1 grow rounded-2xs bg-primary-soft-alpha"
                }), React.createElement(ReactSlider.Thumb, {
                  className: "block size-3.5 cursor-grab rounded-full bg-gray-0 shadow-[inset_0_0_0_2px_var(--color-text)] outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-ring)] active:cursor-grabbing",
                  ariaLabel: label
                }));
}

var make = Slider;

export {
  RadixSlider ,
  make ,
  
}
/* react Not a pure module */
