// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.bs.js";
import * as Utils from "../../Utils.bs.js";
import * as React from "react";

var make = Utils.neverRerender(function (Props) {
      var className = Props.className;
      return React.createElement("svg", {
                  className: Cx.cx([
                        "animate-spin",
                        className
                      ]),
                  fill: "none",
                  viewBox: "0 0 24 24",
                  xmlns: "http://www.w3.org/2000/svg"
                }, React.createElement("circle", {
                      className: "opacity-25",
                      cx: "12",
                      cy: "12",
                      r: "9",
                      stroke: "currentColor",
                      strokeWidth: "2.5"
                    }), React.createElement("path", {
                      d: "M21 12a9 9 0 0 0-9-9",
                      stroke: "currentColor",
                      strokeLinecap: "round",
                      strokeWidth: "2.5"
                    }));
    });

export {
  make ,
  
}
/* make Not a pure module */
