// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactTooltip from "@radix-ui/react-tooltip";

var Provider = {};

var Root = {};

var Trigger = {};

var Portal = {};

var Content = {};

var RadixTooltip = {
  Provider: Provider,
  Root: Root,
  Trigger: Trigger,
  Portal: Portal,
  Content: Content
};

function Tooltip$Provider(Props) {
  var children = Props.children;
  return React.createElement(ReactTooltip.Provider, {
              children: children,
              delayDuration: 400
            });
}

var Provider$1 = {
  make: Tooltip$Provider
};

function Tooltip(Props) {
  var children = Props.children;
  var content = Props.content;
  var shortcut = Props.shortcut;
  var asChildOpt = Props.asChild;
  var asChild = asChildOpt !== undefined ? asChildOpt : true;
  return React.createElement(ReactTooltip.Root, {
              children: null
            }, React.createElement(ReactTooltip.Trigger, {
                  children: children,
                  asChild: asChild
                }), React.createElement(ReactTooltip.Portal, {
                  children: React.createElement(ReactTooltip.Content, {
                        children: null,
                        className: "z-50 flex max-w-[300px] select-none items-center gap-2 rounded-md bg-gray-700 px-2 py-0.5 text-sm text-gray-0 shadow-md animate-tooltip-in",
                        sideOffset: 8
                      }, content, shortcut !== undefined ? React.createElement("kbd", {
                              className: "font-sans text-xs text-gray-300"
                            }, shortcut) : null)
                }));
}

var make = Tooltip;

export {
  RadixTooltip ,
  Provider$1 as Provider,
  make ,
  
}
/* react Not a pure module */
