// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FontIcon from "./FontIcon";
import * as LockIcon from "./LockIcon";
import * as PlayIcon from "./PlayIcon";
import * as PauseIcon from "./PauseIcon";
import * as MagnetIcon from "./MagnetIcon";
import * as VolumeIcon from "./VolumeIcon";
import MagnetSvg from "./magnet.svg";
import * as CaptionsIcon from "./CaptionsIcon";
import * as CollapseIcon from "./CollapseIcon";
import * as GridViewIcon from "./GridViewIcon";
import * as ListViewIcon from "./ListViewIcon";
import * as PlayBackIcon from "./PlayBackIcon";
import * as FullScreenIcon from "./FullScreenIcon";
import * as MusicalNoteIcon from "./MusicalNoteIcon";

var make = MusicalNoteIcon.MusicalNoteIcon;

var MusicalNotesIcon = {
  make: make
};

var make$1 = FontIcon.FontIcon;

var FontIcon$1 = {
  make: make$1
};

var make$2 = CaptionsIcon.CaptionsIcon;

var CaptionsIcon$1 = {
  make: make$2
};

var make$3 = PlayIcon.PlayIcon;

var PlayIcon$1 = {
  make: make$3
};

var make$4 = PlayBackIcon.PlayBackIcon;

var PlayBackIcon$1 = {
  make: make$4
};

var make$5 = VolumeIcon.VolumeIcon;

var VolumeIcon$1 = {
  make: make$5
};

var make$6 = MagnetIcon.MagnetIcon;

var MagnetIcon$1 = {
  make: make$6
};

var make$7 = FullScreenIcon.FullScreenIcon;

var FullScreenIcon$1 = {
  make: make$7
};

var make$8 = CollapseIcon.CollapseIcon;

var CollapseIcon$1 = {
  make: make$8
};

var make$9 = PauseIcon.PauseIcon;

var PauseIcon$1 = {
  make: make$9
};

var make$10 = GridViewIcon.GridViewIcon;

var GridViewIcon$1 = {
  make: make$10
};

var make$11 = ListViewIcon.ListViewIcon;

var ListViewIcon$1 = {
  make: make$11
};

var make$12 = LockIcon.LockIcon;

var LockIcon$1 = {
  make: make$12
};

var magnetRawIcon = MagnetSvg;

export {
  MusicalNotesIcon ,
  FontIcon$1 as FontIcon,
  CaptionsIcon$1 as CaptionsIcon,
  PlayIcon$1 as PlayIcon,
  PlayBackIcon$1 as PlayBackIcon,
  VolumeIcon$1 as VolumeIcon,
  MagnetIcon$1 as MagnetIcon,
  FullScreenIcon$1 as FullScreenIcon,
  CollapseIcon$1 as CollapseIcon,
  PauseIcon$1 as PauseIcon,
  GridViewIcon$1 as GridViewIcon,
  ListViewIcon$1 as ListViewIcon,
  LockIcon$1 as LockIcon,
  magnetRawIcon ,
  
}
/* make Not a pure module */
