[package]
name = "e2e-tests"
version = "1.0.0-beta.6.rc-3.2"
edition = "2024"

[dependencies]
fframes.workspace = true
lazy_static = "1.4.0"
rayon = "1.5.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fframes_renderer = { path = "../fframes-renderer" }

[lib]
name = "e2e_test_video"
path = "src/lib.rs"
