// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UseDebounce from "use-debounce";

function useThrottle(val, ms) {
  return UseDebounce.useDebounce(val, ms, {
    maxWait: ms,
  });
}

export { useThrottle };
/* use-debounce Not a pure module */
