[package]
name = "audio-announce-editor-bridge-example"
version = "1.0.0-beta.6.rc-3.2"
authors = ["Dmitriy Kovalenko <dmtr.kovalenko@outlook.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "./lib.rs"

[dependencies]
wasm-bindgen = "0.2.95"
fframes-editor-controller = { path = "../../../../fframes-editor-controller" }
audio-announce-example = { path = "../../", default-features = false }
