[package]
name = "fframes-media-loaders"
version = "1.0.0-beta.4"
description = "Media loaders used by different fframes packages. This crate is not meant to be used directly."
authors = ["Dmitriy Kovalenko <dmtr.kovalenko@outlook.com>"]
edition = "2021"
license = "MIT"
homepage = "https://fframes.studio"

[lib]

[dependencies]
quote = { version = "1.0.9", optional = true }
webvtt-parser.workspace = true
bytemuck = { version = "1.13.1", features = ["derive"] }
ttf-parser = "0.19.1"
wasm-bindgen.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ffmpeg-sys-fframes.workspace = true
image = { version = "0.24.6", default-features = false, features = [
  "png",
  "jpeg",
] }
usvgr.workspace = true
libc = "0.2.159"

[features]
h264 = ["ffmpeg-sys-fframes/build-lib-x264"]
h265 = ["ffmpeg-sys-fframes/build-lib-x265"]
videotoolbox = ["ffmpeg-sys-fframes/build-videotoolbox"]
audiotoolbox = ["ffmpeg-sys-fframes/build-audiotoolbox"]
aac = ["ffmpeg-sys-fframes/build-lib-aacplus"]
mp3lame = ["ffmpeg-sys-fframes/build-lib-mp3lame"]
opus = ["ffmpeg-sys-fframes/build-lib-opus"]
vpx = ["ffmpeg-sys-fframes/build-lib-vpx"]

# licensing stuff
libav-agree-gpl = ["ffmpeg-sys-fframes/build-license-gpl"]
libav-agree-nonfree = ["ffmpeg-sys-fframes/build-license-nonfree"]
libav-agree-version3 = ["ffmpeg-sys-fframes/build-license-version3"]
