[package]
name = "low-poly-art-example"
version = "1.0.0-beta.6.rc-2.1"
edition = "2021"

[dependencies]
fframes.workspace = true
libm="0.2.1"
rand="0.8.5"
getrandom = { version = "0.2.15", features = ["js"] }

[dev-dependencies]
fframes_test_utils = {path="../../fframes-test-utils"}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fframes_renderer ={path="../../fframes-renderer"}

[features]
default=["renderer"]
renderer=["fframes/compile-time-svgtree"]

[lib]
name = "low_poly_art_example"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "low_poly_art_example_bin"
path = "src/main.rs"
required-features=["renderer"]
