[package]
version = "1.0.0-beta.1"
name = "svgr-macro"
edition = "2018"
description = "A macro for generating SVG trees at compile time"
license = "MIT"
homepage = "https://fframes.studio"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1.0.23"
syn = { version = "1", features = ["full", "parsing", "extra-traits"] }
uuid = { version = "0.8", features = ["v4"] }
usvgr = { workspace = true, default-features = false, features = ["proc-macro"] }
proc-macro-crate = "1.2.1"
lazy_static = "1.4.0"
rust-fuzzy-search = "0.1.0"

[dev-dependencies]
criterion = "0.3"

[features]
compile-time-svgtree = []
