[package]
name = "tiktok-example"
version = "1.0.0-beta.4"
edition = "2021"

[dependencies]
fframes = {path="../../fframes"}
tiktok-media ={path="./media"}
libm="0.2.8"

[features]
default=["renderer"]
renderer=["fframes/compile-time-svgtree"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fframes_renderer ={path="../../fframes-renderer"}

[lib]
name = "tiktok_example"
path = "src/lib.rs"

[[bin]]
name = "tiktok_example_bin"
path = "src/main.rs"
required-features=["renderer"]
