[package]
name = "fframes-media-dir-macro"
version = "1.0.0-beta.6.rc-3.2"
edition = "2024"
description = "A macro for generating SVG trees at compile time"
license = "MIT"
homepage = "https://fframes.studio"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.2.0"
proc-macro2 = "1"
quote = "1.0.38"
syn = { version = "2.0.98", features = [
  "full",
  "parsing",
  "extra-traits",
  "proc-macro",
] }
fframes-media-loaders.workspace = true
bytemuck = "1.21.0"
base64 = "0.22.1"

[features]
nightly = []
metadata = []
