// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Player from "./Player.bs.js";
import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as MediaLoader from "./services/mediaLoader.bs.js";
import * as Webapi__Dom__Window from "bs-webapi/src/Webapi/Dom/Webapi__Dom__Window.bs.js";
import * as Webapi__Dom__EventTarget from "bs-webapi/src/Webapi/Dom/Webapi__Dom__EventTarget.bs.js";

var DocumentEvent = Webapi__Dom__EventTarget.Impl({});

var editorContext = React.createContext(undefined);

var providerElement = editorContext.Provider;

function useEditorContext(param) {
  var context = React.useContext(editorContext);
  if (context !== undefined) {
    return context;
  } else {
    return Pervasives.failwith("Missing editorContext.");
  }
}

function MakeEditorContext(Wasm) {
  var PlayerObserver = Player.MakePlayer(Wasm);
  var EditorContext$MakeEditorContext = function (Props) {
    var children = Props.children;
    React.useLayoutEffect((function () {
            return Curry._1(MediaLoader.MediaLoaderObserver.subscribe, (function (state) {
                          var player = Curry._1(PlayerObserver.get, undefined);
                          if (state.allMediaLoaded && player.playState === /* CantPlay */3) {
                            Curry._1(PlayerObserver.dispatch, /* AllowPlay */0);
                            return Curry._1(PlayerObserver.dispatch, {
                                        TAG: /* NewFrame */1,
                                        _0: player.frame
                                      });
                          }
                          
                        }));
          }), []);
    var usePlayer = function (param) {
      return [
              Curry._1(PlayerObserver.useObservable, undefined),
              PlayerObserver.dispatch
            ];
    };
    return React.createElement(providerElement, {
                value: {
                  wasmController: Wasm.controller,
                  videoMeta: Wasm.videoMeta,
                  options: Wasm.options,
                  usePlayer: usePlayer
                },
                children: children
              });
  };
  return {
          PlayerObserver: PlayerObserver,
          make: EditorContext$MakeEditorContext
        };
}

function makeEditorContextComponent(wasmController, videoMeta, options) {
  var Wasm = {
    videoMeta: videoMeta,
    controller: wasmController,
    options: options
  };
  var PlayerObserver = Player.MakePlayer(Wasm);
  var EditorContext$MakeEditorContext = function (Props) {
    var children = Props.children;
    React.useLayoutEffect((function () {
            return Curry._1(MediaLoader.MediaLoaderObserver.subscribe, (function (state) {
                          var player = Curry._1(PlayerObserver.get, undefined);
                          if (state.allMediaLoaded && player.playState === /* CantPlay */3) {
                            Curry._1(PlayerObserver.dispatch, /* AllowPlay */0);
                            return Curry._1(PlayerObserver.dispatch, {
                                        TAG: /* NewFrame */1,
                                        _0: player.frame
                                      });
                          }
                          
                        }));
          }), []);
    var usePlayer = function (param) {
      return [
              Curry._1(PlayerObserver.useObservable, undefined),
              PlayerObserver.dispatch
            ];
    };
    return React.createElement(providerElement, {
                value: {
                  wasmController: wasmController,
                  videoMeta: videoMeta,
                  options: options,
                  usePlayer: usePlayer
                },
                children: children
              });
  };
  return function (children) {
    return React.createElement(EditorContext$MakeEditorContext, {
                children: children
              });
  };
}

export {
  DocumentEvent ,
  editorContext ,
  providerElement ,
  useEditorContext ,
  MakeEditorContext ,
  makeEditorContextComponent ,
  
}
/* DocumentEvent Not a pure module */
