// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Icons from "./ui/icons/Icons.bs.js";
import * as Utils from "./Utils.bs.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as MediaLoader from "./services/mediaLoader.bs.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";

var iconContainerClassName = "overflow-hidden bg-gray-400 bg-gradient-to-tr from-indigo-400 to-pink-400 flex justify-center items-center";

function MediaList$LoadedMediaIcon(Props) {
  var media = Props.media;
  var variant = Props.variant;
  var style = variant ? ({
        height: "2.5rem",
        width: "2.5rem",
        borderRadius: "0.75rem"
      }) : ({
        height: "7.4rem",
        width: "7.4rem",
        borderRadius: "1.35rem"
      });
  var iconClassName = variant ? "h-[60%]" : "h-[40%]";
  if (media.TAG === /* Image */2) {
    return React.createElement("div", {
                className: Cx.cx([
                      "bg-cover bg-no-repeat bg-center",
                      iconContainerClassName
                    ]),
                style: Object.assign({}, {
                      backgroundImage: "url(" + media._0.src + ")"
                    }, style)
              });
  }
  var tmp;
  switch (media.TAG | 0) {
    case /* Font */0 :
        tmp = React.createElement(Icons.FontIcon.make, {
              color: "currentColor",
              className: iconClassName
            });
        break;
    case /* Subtitles */1 :
        tmp = React.createElement(Icons.CaptionsIcon.make, {
              color: "currentColor",
              className: iconClassName
            });
        break;
    case /* Image */2 :
        tmp = null;
        break;
    case /* Audio */3 :
        tmp = React.createElement(Icons.MusicalNotesIcon.make, {
              color: "currentColor",
              className: iconClassName
            });
        break;
    
  }
  return React.createElement("div", {
              className: iconContainerClassName,
              style: style
            }, tmp);
}

var LoadedMediaIcon = {
  iconContainerClassName: iconContainerClassName,
  make: MediaList$LoadedMediaIcon
};

function stringifyFontWeight(weight) {
  if (weight >= 500) {
    if (weight < 701) {
      if (weight > 699 || weight < 501) {
        if (weight >= 700) {
          return "Bold";
        } else {
          return "Medium";
        }
      } else if (weight !== 600) {
        return "";
      } else {
        return "Semi Bold";
      }
    } else if (weight !== 800) {
      if (weight !== 900) {
        return "";
      } else {
        return "Black";
      }
    } else {
      return "Extra bold";
    }
  } else if (weight >= 201) {
    if (weight !== 300) {
      if (weight !== 400) {
        return "";
      } else {
        return "Regular";
      }
    } else {
      return "Light";
    }
  } else if (weight !== 100) {
    if (weight >= 200) {
      return "Extra light";
    } else {
      return "";
    }
  } else {
    return "Thin";
  }
}

function MediaList$LoadedMedia(Props) {
  var name = Props.name;
  var media = Props.media;
  var variant = Props.variant;
  var tmp;
  switch (media.TAG | 0) {
    case /* Font */0 :
        var fontInfo = media._0;
        tmp = fontInfo.style === "normal" ? fontInfo.name + " (" + stringifyFontWeight(fontInfo.weight) + ", " + fontInfo.unicodeRange + ")" : (
            variant ? fontInfo.name + " (" + fontInfo.style + ", " + stringifyFontWeight(fontInfo.weight) + ", " + fontInfo.unicodeRange + ")" : fontInfo.name
          );
        break;
    case /* Subtitles */1 :
        tmp = String(media._0) + " phrases";
        break;
    case /* Image */2 :
        var match = media._0;
        tmp = String(match.width) + "x" + String(match.height);
        break;
    case /* Audio */3 :
        var match$1 = media._0;
        tmp = Utils.Duration.formatSeconds(match$1.duration) + ", " + String(match$1.sampleRate) + "hz";
        break;
    
  }
  return React.createElement("li", {
              className: Cx.cx([variant ? "py-2 h-16 2xl:h-20 flex space-x-2 px-6" : "w-32 flex flex-col space-y-2"]),
              title: name
            }, React.createElement(MediaList$LoadedMediaIcon, {
                  media: media,
                  variant: variant
                }), React.createElement("div", {
                  className: "ml-0.5 flex flex-col"
                }, React.createElement("p", {
                      className: Cx.cx([
                            "text-gray-300 2xl:text-lg",
                            variant ? "line-clamp-3" : "truncate"
                          ])
                    }, name), React.createElement("p", {
                      className: "text-gray-500 text-xs 2xl:text-base truncate"
                    }, tmp)));
}

var LoadedMedia = {
  make: MediaList$LoadedMedia
};

function MediaList$Loading(Props) {
  var name = Props.name;
  return React.createElement("div", undefined, React.createElement("p", undefined, name));
}

var Loading = {
  make: MediaList$Loading
};

function memo(__x) {
  return React.memo(__x, (function (propsA, propsB) {
                return propsA.variant === propsB.variant;
              }));
}

var make = memo(function (Props) {
      var variant = Props.variant;
      var mediaState = Curry._1(MediaLoader.MediaLoaderObserver.useObservable, undefined);
      return React.createElement("ul", {
                  className: Cx.cx([variant ? "divide-y divide-gray-800 -mx-6" : "flex flex-wrap gap-x-6 gap-y-4"])
                }, Belt_Array.map(Belt_MapString.keysToArray(mediaState.mediaList), (function (name) {
                        var media = Belt_MapString.getExn(mediaState.mediaList, name);
                        switch (media.TAG | 0) {
                          case /* Loading */0 :
                              return React.createElement(MediaList$Loading, {
                                          name: name,
                                          key: name
                                        });
                          case /* Media */1 :
                              return React.createElement(MediaList$LoadedMedia, {
                                          name: name,
                                          media: media._0,
                                          variant: variant,
                                          key: name
                                        });
                          case /* Error */2 :
                              return null;
                          
                        }
                      })));
    });

export {
  LoadedMediaIcon ,
  stringifyFontWeight ,
  LoadedMedia ,
  Loading ,
  memo ,
  make ,
  
}
/* make Not a pure module */
