// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Icons from "./ui/icons/Icons.bs.js";
import * as Utils from "./Utils.bs.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as MediaLoader from "./services/mediaLoader.bs.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";

var iconClassName = "overflow-hidden bg-gray-400 h-10 w-10 2xl:h-12 2xl:w-12 rounded-xl bg-gradient-to-r from-indigo-400 to-pink-400 flex justify-center items-center";

function MediaList$LoadedMediaIcon(Props) {
  var media = Props.media;
  if (media.TAG === /* Image */2) {
    return React.createElement("div", {
                className: Cx.cx([
                      "bg-cover bg-no-repeat bg-center",
                      iconClassName
                    ]),
                style: {
                  backgroundImage: "url(" + media._0.src + ")"
                }
              });
  }
  var tmp;
  switch (media.TAG | 0) {
    case /* Font */0 :
        tmp = React.createElement(Icons.FontIcon.make, {
              color: "currentColor",
              className: "h-7 w-7"
            });
        break;
    case /* Subtitles */1 :
        tmp = React.createElement(Icons.CaptionsIcon.make, {
              color: "currentColor",
              className: "h-7 w-7"
            });
        break;
    case /* Image */2 :
        tmp = null;
        break;
    case /* Audio */3 :
        tmp = React.createElement(Icons.MusicalNotesIcon.make, {
              color: "currentColor",
              className: "h-7 w-7"
            });
        break;
    
  }
  return React.createElement("div", {
              className: iconClassName
            }, tmp);
}

var LoadedMediaIcon = {
  iconClassName: iconClassName,
  make: MediaList$LoadedMediaIcon
};

function stringifyFontWeight(weight) {
  if (weight >= 500) {
    if (weight < 701) {
      if (weight > 699 || weight < 501) {
        if (weight >= 700) {
          return "Bold";
        } else {
          return "Medium";
        }
      } else if (weight !== 600) {
        return "";
      } else {
        return "Semi Bold";
      }
    } else if (weight !== 800) {
      if (weight !== 900) {
        return "";
      } else {
        return "Black";
      }
    } else {
      return "Extra bold";
    }
  } else if (weight >= 201) {
    if (weight !== 300) {
      if (weight !== 400) {
        return "";
      } else {
        return "Regular";
      }
    } else {
      return "Light";
    }
  } else if (weight !== 100) {
    if (weight >= 200) {
      return "Extra light";
    } else {
      return "";
    }
  } else {
    return "Thin";
  }
}

function MediaList$LoadedMedia(Props) {
  var name = Props.name;
  var media = Props.media;
  var tmp;
  switch (media.TAG | 0) {
    case /* Font */0 :
        var fontInfo = media._0;
        tmp = fontInfo.style === "normal" ? fontInfo.name + " (" + stringifyFontWeight(fontInfo.weight) + ", " + fontInfo.unicodeRange + ")" : fontInfo.name + " (" + fontInfo.style + ", " + stringifyFontWeight(fontInfo.weight) + ", " + fontInfo.unicodeRange + ")";
        break;
    case /* Subtitles */1 :
        tmp = String(media._0) + " phrases";
        break;
    case /* Image */2 :
        var match = media._0;
        tmp = String(match.width) + "x" + String(match.height);
        break;
    case /* Audio */3 :
        var match$1 = media._0;
        tmp = Utils.Duration.formatSeconds(match$1.duration) + ", " + String(match$1.sampleRate) + "hz";
        break;
    
  }
  return React.createElement("div", {
              className: "flex space-x-2"
            }, React.createElement(MediaList$LoadedMediaIcon, {
                  media: media
                }), React.createElement("div", {
                  className: "flex flex-col"
                }, React.createElement("p", {
                      className: "text-gray-300 2xl:text-lg"
                    }, name), React.createElement("p", {
                      className: "text-gray-500 text-xs 2xl:text-base"
                    }, tmp)));
}

var LoadedMedia = {
  make: MediaList$LoadedMedia
};

function MediaList$Loading(Props) {
  var name = Props.name;
  return React.createElement("div", undefined, React.createElement("p", undefined, name));
}

var Loading = {
  make: MediaList$Loading
};

function memo(__x) {
  return React.memo(__x, (function (param, param$1) {
                return true;
              }));
}

var make = React.memo((function (Props) {
        var mediaState = Curry._1(MediaLoader.MediaLoaderObserver.useObservable, undefined);
        return React.createElement("ul", {
                    className: "divide-y divide-gray-800"
                  }, Belt_Array.map(Belt_MapString.keysToArray(mediaState.mediaList), (function (name) {
                          var media = Belt_MapString.getExn(mediaState.mediaList, name);
                          var tmp;
                          switch (media.TAG | 0) {
                            case /* Loading */0 :
                                tmp = React.createElement(MediaList$Loading, {
                                      name: name
                                    });
                                break;
                            case /* Media */1 :
                                tmp = React.createElement(MediaList$LoadedMedia, {
                                      name: name,
                                      media: media._0
                                    });
                                break;
                            case /* Error */2 :
                                tmp = null;
                                break;
                            
                          }
                          return React.createElement("li", {
                                      key: name,
                                      className: "px-4 py-2 h-16 2xl:h-20 flex flex-col justify-center"
                                    }, tmp);
                        })));
      }), (function (param, param$1) {
        return true;
      }));

export {
  LoadedMediaIcon ,
  stringifyFontWeight ,
  LoadedMedia ,
  Loading ,
  memo ,
  make ,
  
}
/* make Not a pure module */
