// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "./Utils.bs.js";
import * as Js__Int from "rescript-js/src/Js__Int.bs.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Dom_storage from "rescript/lib/es6/dom_storage.js";
import * as MediaLoader from "./services/mediaLoader.bs.js";
import * as UseObservable from "./hooks/useObservable.bs.js";
import * as AnimationRuntime from "./services/AnimationRuntime.bs.js";

var currentFps = {
  contents: undefined
};

function MakePlayer(Wasm) {
  var previousSavedFrame = Utils.$$Option.unwrapOr(Utils.$$Option.flatten(Belt_Option.map(Dom_storage.getItem("fframe", localStorage), Js__Int.fromString)), 0);
  var savedValue = Dom_storage.getItem("ffvolume", localStorage);
  var volume = savedValue !== undefined ? (
      Wasm.videoMeta.hasAudio ? Number(savedValue) : undefined
    ) : (
      Wasm.videoMeta.hasAudio ? 0.6 : undefined
    );
  var state = Curry._1(MediaLoader.MediaLoaderObserver.get, undefined);
  var initial = state.allMediaLoaded ? ({
        frame: previousSavedFrame,
        startPlayingFrame: previousSavedFrame,
        playState: /* WaitingForAction */2,
        fpsLimit: Wasm.videoMeta.fps,
        svg: Utils.$$Option.some(Curry._1(Wasm.controller.render_frame, BigInt(0))),
        volume: volume
      }) : ({
        frame: previousSavedFrame,
        startPlayingFrame: previousSavedFrame,
        playState: /* CantPlay */3,
        fpsLimit: Wasm.videoMeta.fps,
        svg: undefined,
        volume: volume
      });
  var PlayerState = {
    previousSavedFrame: previousSavedFrame,
    volume: volume,
    initial: initial
  };
  var include = UseObservable.Pubsub({
        initial: initial
      });
  var get = include.get;
  var set = include.set;
  var reducer = function (action) {
    var state = Curry._1(get, undefined);
    if (typeof action === "number") {
      switch (action) {
        case /* AllowPlay */0 :
            return {
                    frame: state.frame,
                    startPlayingFrame: state.startPlayingFrame,
                    playState: /* WaitingForAction */2,
                    fpsLimit: state.fpsLimit,
                    svg: state.svg,
                    volume: state.volume
                  };
        case /* Play */1 :
            if (state.frame <= 0 || state.frame >= Wasm.videoMeta.durationInFrames) {
              return {
                      frame: 0,
                      startPlayingFrame: state.startPlayingFrame,
                      playState: /* Playing */0,
                      fpsLimit: state.fpsLimit,
                      svg: state.svg,
                      volume: state.volume
                    };
            } else {
              return {
                      frame: state.frame,
                      startPlayingFrame: state.frame,
                      playState: /* Playing */0,
                      fpsLimit: state.fpsLimit,
                      svg: state.svg,
                      volume: state.volume
                    };
            }
        case /* Pause */2 :
            return {
                    frame: state.frame,
                    startPlayingFrame: state.startPlayingFrame,
                    playState: /* Paused */1,
                    fpsLimit: state.fpsLimit,
                    svg: state.svg,
                    volume: state.volume
                  };
        
      }
    } else {
      switch (action.TAG | 0) {
        case /* Seek */0 :
        case /* NewFrame */1 :
            break;
        case /* SetVolume */2 :
            return {
                    frame: state.frame,
                    startPlayingFrame: state.startPlayingFrame,
                    playState: state.playState,
                    fpsLimit: state.fpsLimit,
                    svg: state.svg,
                    volume: Utils.$$Option.some(Math.min(Math.max(action._0, 0), 1))
                  };
        
      }
    }
    var frame = action._0;
    if (frame > Wasm.videoMeta.durationInFrames || frame < 0) {
      var svg = Curry._1(Wasm.controller.render_frame, BigInt(0));
      return {
              frame: 0,
              startPlayingFrame: 0,
              playState: /* Paused */1,
              fpsLimit: state.fpsLimit,
              svg: svg,
              volume: state.volume
            };
    }
    var frame$1 = action._0;
    var svg$1 = Curry._1(Wasm.controller.render_frame, BigInt(frame$1));
    var tmp;
    tmp = typeof action === "number" || action.TAG !== /* Seek */0 ? state.startPlayingFrame : action._0;
    return {
            frame: frame$1,
            startPlayingFrame: tmp,
            playState: state.playState,
            fpsLimit: state.fpsLimit,
            svg: svg$1,
            volume: state.volume
          };
  };
  var onFrame = function (dispatch, secondsFromStart) {
    var nextFrame = Math.floor(secondsFromStart * Wasm.videoMeta.fps + Curry._1(get, undefined).startPlayingFrame);
    if (nextFrame !== Curry._1(get, undefined).frame) {
      Curry._1(dispatch, {
            TAG: /* NewFrame */1,
            _0: nextFrame
          });
    }
    return Curry._1(get, undefined).playState === /* Playing */0;
  };
  var sideEffect = function (action, dispatch) {
    var startPlaying = function (currentFrame) {
      Belt_Option.map(Curry._1(get, undefined).volume, AnimationRuntime.AudioRuntime.setVolume);
      AnimationRuntime.AudioRuntime.startAnimation((function (param) {
              return onFrame(dispatch, param);
            }), currentFrame, Wasm.videoMeta);
      
    };
    if (typeof action === "number") {
      switch (action) {
        case /* AllowPlay */0 :
            return ;
        case /* Play */1 :
            if (Curry._1(get, undefined).playState !== /* Playing */0) {
              return startPlaying(Curry._1(get, undefined).frame);
            } else {
              return ;
            }
        case /* Pause */2 :
            return AnimationRuntime.AudioRuntime.stop(undefined);
        
      }
    } else {
      switch (action.TAG | 0) {
        case /* Seek */0 :
            var newFrame = action._0;
            AnimationRuntime.AudioRuntime.stop(undefined);
            startPlaying(newFrame);
            return Dom_storage.setItem("fframe", newFrame.toString(), localStorage);
        case /* NewFrame */1 :
            var newFrame$1 = action._0;
            if (Caml_int32.mod_(newFrame$1, Wasm.videoMeta.fps) === 0) {
              return Dom_storage.setItem("fframe", newFrame$1.toString(), localStorage);
            } else {
              return ;
            }
        case /* SetVolume */2 :
            var value = action._0;
            AnimationRuntime.AudioRuntime.setVolume(value);
            return Dom_storage.setItem("ffvolume", value.toString(), localStorage);
        
      }
    }
  };
  var dispatch = function (action) {
    sideEffect(action, dispatch);
    return Curry._1(set, reducer(action));
  };
  return {
          PlayerState: PlayerState,
          mutableState: include.mutableState,
          listeners: include.listeners,
          get: get,
          set: set,
          nextId: include.nextId,
          subscribe: include.subscribe,
          useObservable: include.useObservable,
          reducer: reducer,
          onFrame: onFrame,
          sideEffect: sideEffect,
          dispatch: dispatch
        };
}

var min_volume = 0;

var max_volume = 1;

export {
  currentFps ,
  min_volume ,
  max_volume ,
  MakePlayer ,
  
}
/* Utils Not a pure module */
