// Generated by ReScript, PLEASE EDIT WITH CARE

import * as VideoFrameDecoder from "./services/VideoFrameDecoder";

function make(prim) {
  return new VideoFrameDecoder.VideoFrameDecoder();
}

export {
  make ,
  
}
/* ./services/VideoFrameDecoder Not a pure module */
