[package]
name = "fframes"
version = "1.0.0-beta.1"
edition = "2021"
author = "Dmitriy Kovalenoko <dmtr.kovalenko@outlook.com>"
license = "MIT"
description = "A video generation framework"
homepage = "https://fframes.studio"

[dependencies]
microfft = "0.4.0"
libm = "0.2.1"
lazy_static = "1.4.0"
num = "0.4.1"
konst = "0.2.15"
roxmltree = "0.14.1"
rangemap = "1.0.3"
ttf-parser = "0.18.0"
lru = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
parking_lot = "0.12.1"
fframes-media-loaders.workspace = true
usvgr.workspace = true
svgr-macro.workspace = true
fframes-media-dir-macro.workspace = true

[dev-dependencies]
futures = "0.3.24"

[lib]
doctest = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.95"

[features]
compile-time-svgtree = ["svgr-macro/compile-time-svgtree"]
media-h264 = ["fframes-media-loaders/h264"]
media-h265 = ["fframes-media-loaders/h265"]
media-videotoolbox = ["fframes-media-loaders/videotoolbox"]
media-audiotoolbox = ["fframes-media-loaders/audiotoolbox"]
media-aac = ["fframes-media-loaders/aac"]
media-mp3lame = ["fframes-media-loaders/mp3lame"]
media-opus = ["fframes-media-loaders/opus"]
media-vpx = ["fframes-media-loaders/vpx"]
media-libav-agree-gpl = ["fframes-media-loaders/libav-agree-gpl"]
media-libav-agree-nonfree = ["fframes-media-loaders/libav-agree-nonfree"]
media-libav-agree-version3 = ["fframes-media-loaders/libav-agree-version3"]
