// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.bs.js";
import * as Web from "../bindings/Web.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Hooks from "../hooks/Hooks.bs.js";
import * as Utils from "../Utils.bs.js";
import * as React from "react";
import * as Player from "../Player.bs.js";
import * as Slider from "./components/Slider.bs.js";
import * as Spinner from "./components/Spinner.bs.js";
import * as Tooltip from "./components/Tooltip.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as IconButton from "./components/IconButton.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as UseDebounce from "../bindings/UseDebounce.bs.js";
import * as ZoomControls from "./Timeline/ZoomControls.bs.js";
import * as EditorContext from "../EditorContext.bs.js";
import * as AnimationRuntime from "../services/AnimationRuntime.bs.js";
import * as UseViewportFollow from "./Timeline/useViewportFollow.bs.js";
import * as Webapi__Dom__Window from "bs-webapi/src/Webapi/Dom/Webapi__Dom__Window.bs.js";
import * as Webapi__Dom__EventTarget from "bs-webapi/src/Webapi/Dom/Webapi__Dom__EventTarget.bs.js";
import * as Icon from "@openai/apps-sdk-ui/components/Icon";

var DocumentEvent = Webapi__Dom__EventTarget.Impl({});

var make = Utils.neverRerender(function (Props) {
      return React.createElement("div", {
                  className: "mx-1 h-5 w-px shrink-0 bg-[var(--color-border)]",
                  role: "separator"
                });
    });

var DockDivider = {
  make: make
};

function getFpsMarker(fps, desiredFps) {
  if (fps !== undefined) {
    if (fps < desiredFps * 0.5) {
      return /* Bad */2;
    } else if (fps < desiredFps * 0.8) {
      return /* Slow */1;
    } else {
      return /* Good */0;
    }
  } else {
    return /* Unknown */3;
  }
}

function Dock(Props) {
  var isFullScreen = Props.isFullScreen;
  var fullScreenToggler = Props.fullScreenToggler;
  var timelineSize = Props.timelineSize;
  var context = EditorContext.useEditorContext(undefined);
  var match = Curry._1(context.usePlayer, undefined);
  var dispatch = match[1];
  var player = match[0];
  var match$1 = Hooks.useToggle(context.options.hideDock);
  var collapsedToggle = match$1[1];
  var followFrameToViewport = timelineSize !== undefined ? UseViewportFollow.useViewportFollow(timelineSize) : undefined;
  var match$2 = UseDebounce.useThrottle(AnimationRuntime.AudioRuntime.runtimeFps.contents, 100);
  var debouncedFps = match$2[0];
  var handlePlayOrPause = Hooks.useEvent(function (param) {
        var match = player.playState;
        Curry._1(dispatch, match !== 0 ? /* Play */1 : /* Pause */2);
        
      });
  var handleSetVolume = Hooks.useEvent(function (value) {
        return Curry._1(dispatch, {
                    TAG: /* SetVolume */2,
                    _0: value
                  });
      });
  var increaseVolume = Hooks.useEvent(function (param) {
        return Belt_Option.forEach(player.volume, (function (volume) {
                      return Curry._1(dispatch, {
                                  TAG: /* SetVolume */2,
                                  _0: Player.validateVolume(volume + context.options.volumeStepFrom0To100 | 0)
                                });
                    }));
      });
  var decreaseVolume = Hooks.useEvent(function (param) {
        return Belt_Option.forEach(player.volume, (function (volume) {
                      return Curry._1(dispatch, {
                                  TAG: /* SetVolume */2,
                                  _0: Player.validateVolume(volume - context.options.volumeStepFrom0To100 | 0)
                                });
                    }));
      });
  var handleSeekLeft = Hooks.useEvent(function (param) {
        var targetFrame = player.frame - Math.imul(context.options.rewindStepInSeconds, context.videoMeta.fps) | 0;
        Curry._1(dispatch, {
              TAG: /* Seek */0,
              _0: targetFrame
            });
        return Belt_Option.forEach(followFrameToViewport, (function (follow) {
                      return Curry._1(follow, targetFrame);
                    }));
      });
  var handleSeekRight = Hooks.useEvent(function (param) {
        var targetFrame = player.frame + Math.imul(context.options.rewindStepInSeconds, context.videoMeta.fps) | 0;
        Curry._1(dispatch, {
              TAG: /* Seek */0,
              _0: targetFrame
            });
        return Belt_Option.forEach(followFrameToViewport, (function (follow) {
                      return Curry._1(follow, targetFrame);
                    }));
      });
  var volumeBeforeMute = React.useRef(60);
  var toggleMute = Hooks.useEvent(function (param) {
        return Belt_Option.forEach(player.volume, (function (volume) {
                      if (volume > 0) {
                        volumeBeforeMute.current = volume;
                        return Curry._1(dispatch, {
                                    TAG: /* SetVolume */2,
                                    _0: 0
                                  });
                      } else {
                        return Curry._1(dispatch, {
                                    TAG: /* SetVolume */2,
                                    _0: volumeBeforeMute.current
                                  });
                      }
                    }));
      });
  var loggedMagnetRef = React.useRef(false);
  var setMagnet = Hooks.useEvent(function (param) {
        if (!loggedMagnetRef.current) {
          console.log("Press 0 or Shift+j to seek to magnet point.");
          loggedMagnetRef.current = true;
        }
        return Curry._1(dispatch, /* SetMagnet */3);
      });
  var seekToStart = Hooks.useEvent(function (param) {
        var targetFrame = Utils.$$Option.unwrapOr(player.magnet, 0);
        Curry._1(dispatch, {
              TAG: /* Seek */0,
              _0: targetFrame
            });
        return Belt_Option.forEach(followFrameToViewport, (function (follow) {
                      return Curry._1(follow, targetFrame);
                    }));
      });
  var seekToEnd = Hooks.useEvent(function (param) {
        var targetFrame = context.videoMeta.durationInFrames;
        Curry._1(dispatch, {
              TAG: /* Seek */0,
              _0: targetFrame
            });
        return Belt_Option.forEach(followFrameToViewport, (function (follow) {
                      return Curry._1(follow, targetFrame);
                    }));
      });
  var switchScene = Hooks.useEvent(function (dir) {
        return Belt_Option.forEach(Belt_Option.flatMap(Caml_option.nullable_to_opt(context.videoMeta.scenesTimeline), (function (timeline) {
                          var nextSceneIndex = dir ? timeline.findIndex(function (scene) {
                                  return scene.start > player.frame;
                                }) : timeline.findIndex(function (scene) {
                                  return scene.end >= player.frame;
                                });
                          return Belt_Array.get(timeline, nextSceneIndex);
                        })), (function (scene) {
                      Curry._1(dispatch, {
                            TAG: /* Seek */0,
                            _0: scene.start
                          });
                      return Belt_Option.forEach(followFrameToViewport, (function (follow) {
                                    return Curry._1(follow, scene.start);
                                  }));
                    }));
      });
  var toggleDock = Hooks.useEvent(function (param) {
        Curry._1(collapsedToggle.toggle, undefined);
        console.log("Press t to show/hide dock controls");
        
      });
  React.useEffect((function () {
          var handleKeydown = function (e) {
            if (!Utils.Bool.invert(Web.$$Element.isFocusable(e.target))) {
              return ;
            }
            var match = e.key;
            switch (match) {
              case " " :
                  return Curry._1(handlePlayOrPause, undefined);
              case "ArrowLeft" :
                  if (e.shiftKey) {
                    return Curry._1(seekToStart, undefined);
                  } else {
                    return Curry._1(handleSeekLeft, undefined);
                  }
              case "ArrowRight" :
                  if (e.shiftKey) {
                    return Curry._1(seekToEnd, undefined);
                  } else {
                    return Curry._1(handleSeekRight, undefined);
                  }
              case "End" :
              case "G" :
                  return Curry._1(seekToEnd, undefined);
              case "0" :
              case "Home" :
              case "J" :
                  return Curry._1(seekToStart, undefined);
              case "S" :
              case "b" :
                  return Curry._1(switchScene, /* Back */0);
              case "F" :
              case "f" :
                  return Curry._1(fullScreenToggler.toggle, undefined);
              case "ArrowDown" :
              case "h" :
                  break;
              case "j" :
                  return Curry._1(handleSeekLeft, undefined);
              case "k" :
                  return Curry._1(handleSeekRight, undefined);
              case "ArrowUp" :
              case "l" :
                  return Curry._1(increaseVolume, undefined);
              case "M" :
              case "m" :
                  return Curry._1(setMagnet, undefined);
              case "T" :
              case "t" :
                  return Curry._1(collapsedToggle.toggle, undefined);
              case "s" :
              case "w" :
                  return Curry._1(switchScene, /* Forth */1);
              default:
                return ;
            }
            if (e.ctrlKey) {
              return Curry._1(toggleMute, undefined);
            } else {
              return Curry._1(decreaseVolume, undefined);
            }
          };
          window.addEventListener("keydown", handleKeydown);
          return (function (param) {
                    window.removeEventListener("keydown", handleKeydown);
                    
                  });
        }), []);
  var rewindStep = String(context.options.rewindStepInSeconds);
  var fps = debouncedFps !== undefined ? Math.min(debouncedFps, context.videoMeta.fps).toFixed(0) : String(context.videoMeta.fps);
  if (match$1[0]) {
    return React.createElement("div", {
                className: "absolute bottom-4 left-1/2 -translate-x-1/2"
              }, React.createElement("div", {
                    className: "rounded-full bg-surface-elevated shadow-[var(--shadow-300),var(--shadow-hairline)]"
                  }, React.createElement(IconButton.make, {
                        label: "Show controls",
                        onClick: toggleDock,
                        children: React.createElement(Icon.ChevronUp, {}),
                        shortcut: "T"
                      })));
  }
  var match$3 = getFpsMarker(debouncedFps, context.videoMeta.fps);
  var tmp;
  switch (match$3) {
    case /* Good */0 :
        tmp = "bg-green-400";
        break;
    case /* Slow */1 :
        tmp = "bg-orange-400";
        break;
    case /* Bad */2 :
        tmp = "bg-red-400";
        break;
    case /* Unknown */3 :
        tmp = "bg-gray-400";
        break;
    
  }
  var match$4 = context.videoMeta.originalFps;
  var originalFps = context.videoMeta.originalFps;
  var match$5 = player.playState;
  var match$6 = player.playState;
  var volume = player.volume;
  var frame = player.magnet;
  return React.createElement("div", {
              "aria-label": "Playback controls",
              className: "absolute bottom-4 left-1/2 flex -translate-x-1/2 items-center gap-1 whitespace-nowrap rounded-full bg-surface-elevated p-1.5 text-default shadow-[var(--shadow-300),var(--shadow-hairline)]",
              role: "toolbar"
            }, React.createElement("div", {
                  className: "flex items-baseline gap-1 px-3 text-sm tabular"
                }, React.createElement("span", {
                      className: "font-medium"
                    }, Utils.Duration.formatFrame(player.frame, context.videoMeta.fps)), React.createElement("span", {
                      className: "text-tertiary"
                    }, "/"), React.createElement("span", {
                      className: "text-secondary"
                    }, Utils.Duration.formatFrame(context.videoMeta.durationInFrames, context.videoMeta.fps))), React.createElement(Tooltip.make, {
                  children: React.createElement("div", {
                        className: "flex h-9 items-center gap-1.5 rounded-full px-2.5 text-xs text-secondary tabular outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-ring)]",
                        tabIndex: 0
                      }, React.createElement("span", {
                            "aria-hidden": true,
                            className: Cx.cx([
                                  "size-1.5 rounded-full transition-colors duration-[400ms]",
                                  tmp
                                ])
                          }), React.createElement("span", {
                            className: "inline-block w-[2ch] text-right"
                          }, fps), React.createElement("span", undefined, "fps"), match$4 !== undefined ? React.createElement(Icon.Lock, {
                              className: "size-3.5"
                            }) : null),
                  content: originalFps !== undefined ? "Preview locked to " + String(context.videoMeta.fps) + " fps, the video renders at " + String(originalFps) + " fps" : "Preview frame rate"
                }), React.createElement(make, {}), React.createElement(IconButton.make, {
                  label: "Back " + rewindStep + "s",
                  onClick: handleSeekLeft,
                  children: React.createElement(Icon.ArrowRotateCcw, {}),
                  shortcut: "←"
                }), React.createElement(IconButton.make, {
                  label: match$5 !== 0 ? (
                      match$5 >= 3 ? "Loading media" : "Play"
                    ) : "Pause",
                  onClick: handlePlayOrPause,
                  children: match$6 !== 0 ? (
                      match$6 >= 3 ? React.createElement(Spinner.make, {
                              className: "size-5"
                            }) : React.createElement(Icon.PlayTriangle, {})
                    ) : React.createElement(Icon.PauseSm, {}),
                  shortcut: "Space",
                  variant: /* Solid */1,
                  size: /* Lg */1
                }), React.createElement(IconButton.make, {
                  label: "Forward " + rewindStep + "s",
                  onClick: handleSeekRight,
                  children: React.createElement(Icon.ArrowRotateCw, {}),
                  shortcut: "→"
                }), React.createElement(make, {}), React.createElement("div", {
                  className: "flex items-center gap-1 pr-3"
                }, volume !== undefined ? React.createElement(IconButton.make, {
                        label: volume === 0 ? "Unmute" : "Mute",
                        onClick: toggleMute,
                        children: volume === 0 ? React.createElement(Icon.SoundOffSpeaker, {}) : React.createElement(Icon.SoundOnReadOutLoudSpeaker, {}),
                        shortcut: "Ctrl ↓",
                        pressed: volume === 0
                      }) : React.createElement(Tooltip.make, {
                        children: React.createElement("span", {
                              className: "inline-flex size-9 items-center justify-center text-disabled outline-none [&>svg]:size-5",
                              tabIndex: 0
                            }, React.createElement(Icon.SoundOffSpeaker, {})),
                        content: "This video has no audio"
                      }), React.createElement(Slider.make, {
                      onValueChange: handleSetVolume,
                      disabled: Belt_Option.isNone(player.volume),
                      value: Utils.$$Option.unwrapOr(player.volume, 0),
                      min: Player.min_volume,
                      max: Player.max_volume,
                      step: 1,
                      label: "Volume"
                    })), React.createElement(make, {}), React.createElement(IconButton.make, {
                  label: frame !== undefined ? (
                      frame === player.frame ? "Remove start pin" : "Move start pin here"
                    ) : "Pin start here",
                  onClick: setMagnet,
                  children: React.createElement(Icon.Pin, {}),
                  shortcut: "M",
                  pressed: Belt_Option.isSome(player.magnet)
                }), React.createElement(ZoomControls.make, {}), React.createElement(IconButton.make, {
                  label: isFullScreen ? "Exit full screen" : "Full screen",
                  onClick: fullScreenToggler.toggle,
                  children: isFullScreen ? React.createElement(Icon.CollapseLg, {}) : React.createElement(Icon.ExpandLg, {}),
                  shortcut: "F"
                }), React.createElement(make, {}), React.createElement(IconButton.make, {
                  label: "Hide controls",
                  onClick: toggleDock,
                  children: React.createElement(Icon.ChevronDown, {}),
                  shortcut: "T"
                }));
}

var make$1 = Dock;

export {
  DocumentEvent ,
  DockDivider ,
  getFpsMarker ,
  make$1 as make,
  
}
/* DocumentEvent Not a pure module */
