// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dock from "./Dock.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Hooks from "../hooks/Hooks.bs.js";
import * as Utils from "../Utils.bs.js";
import * as React from "react";
import * as Timeline from "./Timeline/Timeline.bs.js";
import * as $$MediaList from "../MediaList.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ReactHelmet from "react-helmet";
import * as EditorContext from "../EditorContext.bs.js";
import * as UseEditorLayout from "../hooks/useEditorLayout.bs.js";
import HtmlReactParser from "html-react-parser";

function a(prim) {
  return {};
}

function Editor(Props) {
  var context = EditorContext.useEditorContext(undefined);
  var match = Curry._1(context.usePlayer, undefined);
  var match$1 = Hooks.useToggle(false);
  var layout = Hooks.useEditorLayout(match$1[0]);
  var previewRef = React.useRef(null);
  var videoTitle = React.useMemo((function () {
          var name = Utils.$$Array.last(context.videoMeta.name.split("::"));
          if (name !== undefined) {
            return name;
          } else {
            return "Unknown video";
          }
        }), [context.videoMeta]);
  React.useEffect((function () {
          Belt_Option.forEach(Caml_option.nullable_to_opt(previewRef.current), (function (param) {
                  console.log("Happy video hacking! Your preview will be rendered at", param);
                  
                }));
          
        }), []);
  return React.createElement("div", {
              className: "w-screen h-screen bg-gray-900"
            }, React.createElement(ReactHelmet.Helmet, {
                  children: null
                }, React.createElement("title", undefined, videoTitle), React.createElement("style", {
                      type: "text/css"
                    }, "\n            #editor-preview > svg {\n              transform-origin: top left !important;\n              transform: scale(" + layout.preview.scale.toString() + ") !important\n            }\n          ")), React.createElement("div", {
                  className: "overflow-auto flex justify-center w-full"
                }, Utils.$$Option.unwrapOr(Belt_Option.map(layout.mediaControls, (function (size) {
                            return React.createElement("div", {
                                        className: "col-span-2 h-full overflow-auto flex flex-col py-6 border-r border-gray-800",
                                        style: UseEditorLayout.sizeToStyle(size)
                                      }, React.createElement("h1", {
                                            className: "text-2xl mb-6 font-medium text-white px-6"
                                          }, videoTitle), React.createElement($$MediaList.make, {}));
                          })), null), React.createElement("div", {
                      ref: previewRef,
                      className: "bg-black",
                      id: "editor-preview",
                      style: UseEditorLayout.sizeToStyle(layout.preview)
                    }, HtmlReactParser(Utils.$$Option.unwrapOr(match[0].svg, ""), {
                          htmlparser2: {
                            xmlMode: true
                          }
                        }))), Utils.$$Option.unwrapOr(Belt_Option.map(layout.timeLine, (function (sectionSize) {
                        return React.createElement("div", {
                                    className: "shadow-lg w-screen bg-gray-800",
                                    style: UseEditorLayout.sizeToStyle(sectionSize)
                                  }, React.createElement(Timeline.make, {
                                        sectionSize: sectionSize
                                      }));
                      })), null), React.createElement(Dock.make, {
                  fullScreenToggler: match$1[1]
                }));
}

var make = Editor;

export {
  a ,
  make ,
  
}
/* Dock Not a pure module */
