// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

var applyToDocument = (theme => { document.documentElement.dataset.theme = theme });

var darkQuery = "(prefers-color-scheme: dark)";

function resolve(preference) {
  if (preference === "system") {
    if (window.matchMedia(darkQuery).matches) {
      return /* Dark */1;
    } else {
      return /* Light */0;
    }
  } else if (preference === "light") {
    return /* Light */0;
  } else {
    return /* Dark */1;
  }
}

function toString(theme) {
  if (theme) {
    return "dark";
  } else {
    return "light";
  }
}

function useTheme(preference) {
  var match = React.useState(function () {
        return resolve(preference);
      });
  var setTheme = match[1];
  var theme = match[0];
  React.useEffect((function () {
          Curry._1(setTheme, (function (param) {
                  return resolve(preference);
                }));
          if (preference !== "system") {
            return ;
          }
          var query = window.matchMedia(darkQuery);
          var onChange = function (param) {
            return Curry._1(setTheme, (function (param) {
                          return resolve(preference);
                        }));
          };
          query.addEventListener("change", onChange);
          return (function (param) {
                    query.removeEventListener("change", onChange);
                    
                  });
        }), [preference]);
  React.useLayoutEffect((function () {
          applyToDocument(theme ? "dark" : "light");
          
        }), [theme]);
  return theme;
}

var context = React.createContext(/* Dark */1);

var provider = context.Provider;

function Theme$Provider(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var Provider = {
  make: Theme$Provider
};

function use(param) {
  return React.useContext(context);
}

var fontSans = "ui-sans-serif, -apple-system, system-ui, \"Segoe UI\", \"Noto Sans\", Helvetica, Arial, sans-serif";

var canvasFont = "12px " + fontSans;

var canvasFontMedium = "500 12px " + fontSans;

var scenes = [
  "#0285ff",
  "#04b84c",
  "#fb6a22",
  "#924ff7",
  "#ff66ad",
  "#ffc300",
  "#fa423e"
];

var dark = {
  text: "#ffffff",
  textSecondary: "#afafaf",
  textTertiary: "#8f8f8f",
  border: "rgb(255 255 255 / 0.12)",
  softAlpha: "rgb(255 255 255 / 0.08)",
  surface: "#181818",
  accent: "#339cff",
  scenes: scenes
};

var light = {
  text: "#0d0d0d",
  textSecondary: "#5d5d5d",
  textTertiary: "#8f8f8f",
  border: "rgb(13 13 13 / 0.1)",
  softAlpha: "rgb(13 13 13 / 0.05)",
  surface: "#f9f9f9",
  accent: "#0169cc",
  scenes: scenes
};

function palette(theme) {
  if (theme) {
    return dark;
  } else {
    return light;
  }
}

export {
  applyToDocument ,
  darkQuery ,
  resolve ,
  toString ,
  useTheme ,
  context ,
  provider ,
  Provider ,
  use ,
  fontSans ,
  canvasFont ,
  canvasFontMedium ,
  scenes ,
  dark ,
  light ,
  palette ,
  
}
/* context Not a pure module */
