name: Build

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: rottenberg/ffmpeg:5.1.2-ubuntu2004
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust"
          cache-on-failure: true

      # TODO support macos
      # - name: Configure Homebrew cache
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/Library/Caches/Homebrew/foo--*
      #       ~/Library/Caches/Homebrew/downloads/*--foo-*
      #     key: brew-${{ hashFiles('.github/brew-formulae') }}
      #     restore-keys: brew-

      # - run: brew install ffmpeg
      # - run: brew link --force ffmpeg
      # - run: ffmpeg -version

      - run: sudo add-apt-repository ppa:savoury1/ffmpeg4 -y
      - run: sudo add-apt-repository ppa:savoury1/ffmpeg5 -y
      - run: sudo apt-get install ffmpeg libavformat-dev libavcodec-dev libavutil-dev libavfilter-dev libswscale-dev libavdevice-dev

      - name: Build
        run: just build

      - name: Clippy
        run: just clippy

      # We have to use the Release mode, otherwise it would take forever.
      - name: Test
        run: just test-release

      - name: Upload visual regression results and diff
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: results
          if-no-files-found: error
          path: |
            e2e/frames/results
            e2e/frames/diff
            e2e/out.mp4
