name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: namespace-profile-default
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Spellcheck
        uses: crate-ci/typos@master
        with:
          config: ./typos.toml

  build-rescript:
    name: Build ReScript
    runs-on: namespace-profile-default
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "yarn"

      - name: Install frontend deps
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile --prefer-offline

      # - name: Syncpack
      #   working-directory: fframes-editor
      #   run: yarn syncpack lint
 
      - name: Build frontend
        working-directory: fframes-editor
        run: yarn build 

  build-rust:
    name: Build and Test
    if: github.event_name == 'pull_request'
    continue-on-error: true
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [namespace-profile-default]
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install apt-deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-16 llvm ninja-build libgl1 libgl1-mesa-dev libgles2-mesa-dev libssl-dev libfontconfig1-dev mesa-common-dev libwayland-dev yasm nasm ffmpeg libx264-dev libx265-dev libopus-dev libvpx-dev

      - name: Install Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
         vulkan-query-version: 1.3.204.0
         vulkan-components: Vulkan-Headers, Vulkan-Loader
         vulkan-use-cache: true

      - name: Install brew deps 
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config ffmpeg x264 x265 opus nasm

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 23
          cache: "yarn"

      - name: Install frontend deps
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile --prefer-offline

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with: 
          cache: true
          cache-on-failure: true
          cache-key: "v3-rust"
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Check format
        run: cargo fmt --check

      - name: Build
        run: just clippy

      - name: Check examples wasm build
        run: |
          rustup target add wasm32-unknown-unknown
          just check-examples

      - name: Test
        run: just test

      - name: Upload visual regression results and diff
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: results
          if-no-files-found: ignore
          path: |
            e2e/frames/results
            e2e/frames/diff
            e2e/out.mp4
            */**/_svgr_snapshots/*

  release:
    name: Publish nightly release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: namespace-profile-default
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 23
          cache: "yarn"

      - name: Install frontend deps
        run: |
          npm install -g yarn
          yarn install --frozen-lockfile --prefer-offline

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with: 
          toolchain: stable
          cache: true
          cache-key: "v3-rust"

      - name: Run Release Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git fetch --tags
          bash release.sh "$(git describe --tags $(git rev-list --tags --max-count=1)).rc-$(printf "%02d" $(git rev-list --count $(git describe --tags --abbrev=0)..HEAD))"  

  # not now
  # check-windows-build: 
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #
  #     - name: Install nasm
  #       run: choco install nasm
  #
  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         override: true
  #
  #     - run: cargo check
