name: Build

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:6.0-ubuntu2004
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: apt-get update
      - run: apt install -y build-essential lsb-release wget software-properties-common gnupg
      - run: apt-get install -y curl pkg-config
      - run: bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      - run: curl -fsSL https://deb.nodesource.com/setup_19.x | bash -
      - run: apt-get install -y nodejs
      - run: npm install -g yarn

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust"
          cache-on-failure: true

      # TODO support macos
      # - name: Configure Homebrew cache
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/Library/Caches/Homebrew/foo--*
      #       ~/Library/Caches/Homebrew/downloads/*--foo-*
      #     key: brew-${{ hashFiles('.github/brew-formulae') }}
      #     restore-keys: brew-

      # - run: brew install ffmpeg
      # - run: brew link --force ffmpeg
      # - run: ffmpeg -version

      - name: Build
        run: just build


      - name: Check examples wasm build
        run: 
          cargo install wasm-pack
          just check-examples

      - name: Clippy
        run: just clippy

      # We have to use the Release mode, otherwise it will take forever.
      - name: Test
        run: just test-release

      - name: Upload visual regression results and diff
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: results
          if-no-files-found: error
          path: |
            e2e/frames/results
            e2e/frames/diff
            e2e/out.mp4
